<?php

if (isset($_POST['submit'])) {

	$bkgd = '#'.$_POST['bkgd'];
	$color1 = '#'.$_POST['999'];
	$color2 = '#'.$_POST['000'];
	$color3 = '#'.$_POST['009'];
	$color4 = '#'.$_POST['00F'];
	$color5 = '#'.$_POST['06F'];
	$color6 = '#'.$_POST['099'];
	$color7 = '#'.$_POST['060'];
	$color8 = '#'.$_POST['990'];
	$color9 = '#'.$_POST['520'];
	$color10 = '#'.$_POST['900'];
	$color11 = '#'.$_POST['A50'];
	$color12 = '#'.$_POST['C70'];
	$color13 = '#'.$_POST['909'];
	$color14 = '#'.$_POST['F0F'];
	$color15 = '#'.$_POST['C00'];
	$color16 = '#'.$_POST['F03'];
	$color17 = '#'.$_POST['FF6208'];
	$color18 = '#'.$_POST['F90'];
	
	$theme = array($bkgd, $color1, $color2, $color3, $color4, $color5, $color6, $color7, $color8, $color9, $color10, $color11, $color12, $color13, $color14, $color15, $color16, $color17, $color18);
	$themeString = implode($theme, ',');
	
	header('Content-Type: text/xml;');
	header('Content-Disposition: attachment; filename=Colors.xml');
	
	echo "<!-- generated by Dreamweaver Color Theme Editor: inorganik.net/dw-color-theme-editor -->\n";
	echo "<!-- theme colors: $themeString -->\n";	
	
} ?>
<codeColors>
	<colorGroup>
		<syntaxColor id="CodeColor_HTMLEntity" bold="true" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptSpryKeywords" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptSpryClasses" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CFCommentText" text="<?php echo $color2; ?>" bgcolor="#FF9" />
		<syntaxColor id="CodeColor_JavaJSP" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavaImplicit" text="<?php echo $color8; ?>" />
		<syntaxColor id="CodeColor_JavaOther" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JSPPageOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPTaglibOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPIncludeOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_PHPScriptBlock" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_PHPScriptComment" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_PHPScriptConstant" text="<?php echo $color9; ?>" />
		<syntaxColor id="CodeColor_PHPScriptString" text="<?php echo $color15; ?>" />
		<syntaxColor id="CodeColor_PHPScriptFunctionsKeywords" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_PHPScriptReserved" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_PHPScriptTypes" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_PHPScriptVariables" text="<?php echo $color5; ?>" />
		<syntaxColor id="CodeColor_PHPScriptBuiltinVariables" text="<?php echo $color5; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPDirOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_LibraryText" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_DateText" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_ASPJSNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASPJSKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_SpryAttributes" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_Spry_Tag_Normal" bgcolor="#F8D0AF" />
		<syntaxColor id="CodeColor_Spry_Tag_Hover" bgcolor="#FF9B58" />
		<syntaxColor id="CodeColor_Spry_Tag_Selected" bgcolor="#FF6D0C" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="#FF00FF" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<tagColor id="DWTagLibrary_cfc" text="<?php echo $color10; ?>" />
		<tagColor id="DWTagLibrary_cfml" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirTagKeywords" text="<?php echo $color10; ?>" />
		<tagColor id="DWTagLibrary_aspnetmmtags" text="<?php echo $color10; ?>" />
		<tagColor id="DWTagLibrary_aspnettemplates" text="<?php echo $color10; ?>" />
		<tagColor id="DWTagLibrary_aspnet" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ActionscriptProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptNative" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptNumber" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptFunction" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptBracket" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ActionscriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ActionscriptRemoting" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASCommBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASCommComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ASCommFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASCommNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASCommNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASCommReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASCommString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASRemoteBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASRemoteComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ASRemoteFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASRemoteNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASRemoteNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASRemoteReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASRemoteString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
	</colorGroup>
	<colorGroup doctypes="HTML">
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_AspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<tagColor id="DWTagLibrary_templates" text="<?php echo $color3; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASP-JS">
		<syntaxColor id="CodeColor_ASPDirBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_AspDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirTagKeywords" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_AspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPJSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPJSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_AspJScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASPJSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASPJSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_asp" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_CSharpBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSharpChar" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSharpComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSharpDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_Number" text="<?php echo $color16; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSharpOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBNetComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VB.NetDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBNetOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_VBSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASP-VB">
		<syntaxColor id="CodeColor_ASPDirBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_AspDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirTagKeywords" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_AspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPJSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPJSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_AspJScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASPJSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASPJSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_asp" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_CSharpBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSharpChar" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSharpComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSharpDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_Number" text="<?php echo $color16; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSharpOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBNetComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VB.NetDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBNetOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_VBSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASP.NET_CSharp">
		<syntaxColor id="CodeColor_ASPDirBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_AspDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirTagKeywords" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_AspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPJSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPJSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_AspJScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASPJSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASPJSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_aspnet" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_CSharpBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSharpChar" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSharpComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSharpDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_Number" text="<?php echo $color16; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSharpOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBNetComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VB.NetDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBNetOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_VBSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASP.NET_VB">
		<syntaxColor id="CodeColor_ASPDirBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_AspDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPDirTagKeywords" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPDirString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeAttributes" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_AspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_ASPJSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASPJSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_AspJScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASPJSNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASPJSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASPJSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASPJSString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_aspnet" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_CSharpBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSharpChar" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSharpComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSharpDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_Number" text="<?php echo $color16; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSharpOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBNetComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VB.NetDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBNetOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_VBSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="ColdFusion">
		<tagColor id="DWTagLibrary_cfml" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CFScriptBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CfmlScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CFScriptNative" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CFScriptNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_CFScriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CFCommentText" text="<?php echo $color2; ?>" bgcolor="#FF9" />
		<syntaxColor id="CodeColor_CFScriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CFScriptFunction" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="CFC">
		<tagColor id="DWTagLibrary_cfml" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CFScriptBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CfmlScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CFScriptNative" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CFScriptNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_CFScriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CFScriptString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CFCommentText" text="<?php echo $color2; ?>" bgcolor="#FF9" />
		<syntaxColor id="CodeColor_CFScriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CFScriptFunction" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="JSP">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_JavaComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaImplicit" text="<?php echo $color8; ?>" />
		<syntaxColor id="CodeColor_JavaJSP" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavaNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_JavaOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaOther" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavaReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_jrun" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_JSPIncludeAttributes" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JSPIncludeBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JspIncludeDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPIncludeOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPIncludeString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JSPPageAttributes" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JSPPageBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JspPageDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPPageOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPPageString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JSPTaglibAttributes" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JSPTaglibBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JspTagLibDirDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPTaglibOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JSPTaglibString" text="<?php echo $color7; ?>" />
		<tagColor id="DWTagLibrary_jsp" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="LibraryItem">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="PHP_MySQL">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_DateText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_LibraryText" text="<?php echo $color2; ?>" bgcolor="#FFC" />
		<syntaxColor id="CodeColor_PHPScriptBlock" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_PHPScriptBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_PHPScriptBuiltinVariables" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_PHPScriptComment" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_PHPScriptConstant" text="<?php echo $color9; ?>" />
		<syntaxColor id="CodeColor_PhpScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_PHPScriptFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_PHPScriptFunctionsKeywords" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_PHPScriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_PHPScriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_PHPScriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_PHPScriptReserved" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_PHPScriptString" text="<?php echo $color15; ?>" />
		<syntaxColor id="CodeColor_PHPScriptTypes" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_PHPScriptVariables" text="<?php echo $color5; ?>" />
		<tagColor id="DWTagLibrary_php" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="XSLT">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="DWTagLibrary_html" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<tagColor id="DWTagLibrary_templates" text="<?php echo $color3; ?>" />
		<tagColor id="DWTagLibrary_xslt" text="<?php echo $color3; ?>" />
	</colorGroup>
	<colorGroup doctypes="Actionscript">
		<syntaxColor id="CodeColor_ActionscriptBracket" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ActionScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptFunction" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptNative" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptNumber" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptOperator" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ActionscriptProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptRemoting" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ActionscriptString" text="<?php echo $color4; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASComm">
		<syntaxColor id="CodeColor_ASCommBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASCommComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ActionScriptCommDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASCommFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASCommIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASCommNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASCommNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASCommOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASCommReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASCommString" text="<?php echo $color4; ?>" />
	</colorGroup>
	<colorGroup doctypes="ASRemote">
		<syntaxColor id="CodeColor_ASRemoteBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASRemoteComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_ActionScriptRemoteDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASRemoteFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_ASRemoteIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_ASRemoteNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_ASRemoteNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_ASRemoteOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_ASRemoteReserved" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_ASRemoteString" text="<?php echo $color4; ?>" />
	</colorGroup>
	<colorGroup doctypes="Csharp">
		<syntaxColor id="CodeColor_ASPNetCSharpKeywords" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_CSharpBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSharpChar" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSharpComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSharpDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_CSharpIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_Number" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_CSharpOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_CSharpString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="CSS">
		<syntaxColor id="CodeColor_CSSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_CSSImport" text="<?php echo $color6; ?>" bold="true" />
		<syntaxColor id="CodeColor_CssKeywordImportant" text="<?php echo $color16; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSMedia" text="<?php echo $color10; ?>" bold="true" />
		<syntaxColor id="CodeColor_CSSProperty" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_CSSSelector" text="<?php echo $color14; ?>" />
		<syntaxColor id="CodeColor_CSSString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_CSSValue" text="<?php echo $color4; ?>" />
	</colorGroup>
	<colorGroup doctypes="EDML">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_XMLString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_XMLComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_XMLNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_XMLTag" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_XMLText" text="<?php echo $color2; ?>" />
	</colorGroup>
	<colorGroup doctypes="Java">
		<syntaxColor id="CodeColor_JavaBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_JavaComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavaImplicit" text="<?php echo $color8; ?>" />
		<syntaxColor id="CodeColor_JavaJSP" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavaNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_JavaOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaOther" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavaReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavaString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="JavaScript">
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
	</colorGroup>
	<colorGroup doctypes="SVG">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptBracket" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptClient" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_JavascriptComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_JavaScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptFunction" text="<?php echo $color2; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_JavascriptNative" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_JavascriptNumber" text="<?php echo $color17; ?>" />
		<syntaxColor id="CodeColor_JavascriptOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_JavascriptRegexp" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_JavascriptReserved" text="<?php echo $color3; ?>" bold="true" />
		<syntaxColor id="CodeColor_JavascriptString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_SVGAttr" text="<?php echo $color18; ?>" />
		<syntaxColor id="CodeColor_SVGString" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_SVGComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_SVGNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<tagColor id="SVG tags" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_SVGTag" text="<?php echo $color12; ?>" />
		<syntaxColor id="CodeColor_SVGText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="Text">
		<syntaxColor id="CodeColor_TextText" text="<?php echo $color2; ?>" />
	</colorGroup>
	<colorGroup doctypes="VB">
		<syntaxColor id="CodeColor_VBNetBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBNetComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBNetConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VB.NetDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBNetNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBNetNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBNetOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBNetString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="VBScript">
		<syntaxColor id="CodeColor_VBSBlock" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSBracket" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_VBSComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_VBSConstants" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_VBScriptDefaultText" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSFunction" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSIdentifier" text="<?php echo $color2; ?>" />
		<syntaxColor id="CodeColor_VBSNative" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_VBSNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_VBSOperator" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSReserved" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_VBSString" text="<?php echo $color7; ?>" />
	</colorGroup>
	<colorGroup doctypes="WML">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_HTMLString" text="<?php echo $color4; ?>" />
		<syntaxColor id="CodeColor_HTMLComment" text="<?php echo $color1; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<syntaxColor id="CodeColor_HTMLNumber" text="<?php echo $color4; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLTag" text="<?php echo $color3; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<syntaxColor id="CodeColor_HTMLEntity" text="<?php echo $color2; ?>" bold="true" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<syntaxColor id="CodeColor_HTMLText" text="<?php echo $color2; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
	</colorGroup>
	<colorGroup doctypes="XML">
		<tagColor id="CodeColor_CFScriptTag" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLAnchor" text="<?php echo $color7; ?>" />
		<tagColor id="CodeColor_HTMLForm" text="<?php echo $color18; ?>" />
		<tagColor id="CodeColor_HTMLImage" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLObject" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLScript" text="<?php echo $color10; ?>" />
		<tagColor id="CodeColor_HTMLStyle" text="<?php echo $color13; ?>" />
		<tagColor id="CodeColor_HTMLTable" text="<?php echo $color6; ?>" />
		<tagColor id="CodeColor_SVGTagGroup" text="<?php echo $color11; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentText" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateCommentAttr" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_TemplateText" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_XMLString" text="<?php echo $color7; ?>" />
		<syntaxColor id="CodeColor_XMLComment" text="<?php echo $color1; ?>" />
		<syntaxColor id="CodeColor_XMLNumber" text="<?php echo $color16; ?>" />
		<syntaxColor id="CodeColor_XMLTag" text="<?php echo $color3; ?>" />
		<syntaxColor id="CodeColor_XMLText" text="<?php echo $color2; ?>" />
	</colorGroup>
</codeColors>
